spring:
  mvc:
    static-path-pattern: /resources
  datasource:
    url: jdbc:mysql://localhost:3306/grupo-12-oo2
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    